### PR TITLE
Add Migration to Cold Storage helper

### PR DESCRIPTION
**Pull request by angristan**
Add `c14 migrate` command to prepare for EOL for the C14 legacy product.

TODO:

- [x] Improve example
- [x] Rebase on https://github.com/scaleway/c14-cli/pull/70 (Go update) and add deps
- [x] Add options to specify bucket name and prefix name
- [x] Make bucket creation optional

### CODE REVIEW

**Comment by newtoncorp** [comment]
Maybe add a way to specify a prefix inside a bucket and not create a bucket ?

**Comment by angristan** [comment]
Example:

```sh
> ./c14 ls
NAME                STATUS              UUID
test2               active              2c34b3f1-e0f8-4ced-b695-c9935bba3185
test                busy                3a04741f-f75f-49db-a64d-c5179c7fa092

> ./c14 unfreeze 2c34b3f1-e0f8-4ced-b695-c9935bba3185
2c34b3f1-e0f8-4ced-b695-c9935bba3185[==================================] 150.00%


> ./c14 migrate --s3-profile default precheck 2c34b3f1-e0f8-4ced-b695-c9935bba3185
Using AWS profile default
Making sure all files are < 5 TB for S3 compatibility
Checking S3 API credentials...
Checking if S3 migration destination bucket c14-7f4bc270-d03a-4650-b8ac-e79f8e73d279 exists...
You can use --create-bucket to automatically create the bucket
All good!

> ./c14 migrate --s3-profile default --s3-create-bucket --s3-bucket migration-c14-test precheck 2c34b3f1-e0f8-4ced-b695-c9935bba3185 
Using AWS profile default
Making sure all files are < 5 TB for S3 compatibility
Checking S3 API credentials...
Checking if S3 migration destination bucket migration-c14-test exists...
Creating bucket...
Waiting for bucket "migration-c14-test" to be created...
Bucket "migration-c14-test" successfully created
All good!


> ./c14 migrate --s3-profile default --s3-create-bucket --s3-bucket migration-c14-test generate-rclone-config 2c34b3f1-e0f8-4ced-b695-c9935bba3185
Using AWS profile default
Converting SFTP password for rclone config
Writing config file to /Users/stanislas/rclone-c14-migration_7f4bc270-d03a-4650-b8ac-e79f8e73d279_2c34b3f1-e0f8-4ced-b695-c9935bba3185.conf
The following config file has been generated: 
[c14]
type = sftp
host = xxx.buffer.c14.io
port = 60351
user = c14ssh
pass = xxx
md5sum_command = md5sum
sha1sum_command = sha1sum

[default]
type = s3
provider = Scaleway
env_auth =  true
region = fr-par
endpoint = https://s3.fr-par.scw.cloud
storage_class = GLACIER

> ./c14 migrate --s3-profile default --s3-create-bucket --s3-bucket migration-c14-test rclone-sync 2c34b3f1-e0f8-4ced-b695-c9935bba3185     
Using AWS profile default
Checking if rclone is installed
rclone executable is in /usr/local/bin/rclone
Running sync
Running command: rclone --config=/Users/stanislas/rclone-c14-migration_7f4bc270-d03a-4650-b8ac-e79f8e73d279_2c34b3f1-e0f8-4ced-b695-c9935bba3185.conf sync c14:/buffer/ default:migration-c14-test/2c34b3f1-e0f8-4ced-b695-c9935bba3185 --log-level=INFO
2020/05/26 10:48:23 INFO  : dir2/screenshot_2020-05-05_10-11-55@2x.png: Copied (new)
2020/05/26 10:48:23 INFO  : S3 bucket migration-c14-test path 2c34b3f1-e0f8-4ced-b695-c9935bba3185: Waiting for checks to finish
2020/05/26 10:48:23 INFO  : S3 bucket migration-c14-test path 2c34b3f1-e0f8-4ced-b695-c9935bba3185: Waiting for transfers to finish
2020/05/26 10:48:23 INFO  : IMG_20190903_133904.jpg: Copied (new)
2020/05/26 10:48:23 INFO  : dir2/screenshot_2020-05-05_14-02-24@2x.png: Copied (new)
2020/05/26 10:48:23 INFO  : dir2/screenshot_2020-05-05_13-27-47@2x.png: Copied (new)
2020/05/26 10:48:24 INFO  : dir2/screenshot_2020-05-05_13-27-48@2x.png: Copied (new)
2020/05/26 10:48:24 INFO  : dir2/screenshot_2020-05-05_17-25-58@2x.png: Copied (new)
2020/05/26 10:48:24 INFO  : dir2/screenshot_2020-05-05_16-08-30@2x.png: Copied (new)
2020/05/26 10:48:24 INFO  : dir2/screenshot_2020-05-05_17-32-25@2x.png: Copied (new)
2020/05/26 10:48:24 INFO  : dir1/screenshot_2020-05-06_16-53-53@2x.png: Copied (new)
2020/05/26 10:48:24 INFO  : Waiting for deletions to finish
2020/05/26 10:48:24 INFO  : 
Transferred:       14.198M / 14.198 MBytes, 100%, 8.213 MBytes/s, ETA 0s
Transferred:           10 / 10, 100%
Elapsed time:         1.7s


Sync done.
Please freeze or delete your archive once you made sure it migrated properly.
To freeze the archive, run: c14 freeze 2c34b3f1-e0f8-4ced-b695-c9935bba3185

> c14 freeze 2c34b3f1-e0f8-4ced-b695-c9935bba3185
330606b4-0492-4441-8004-8f3c9f804c30[==================================] 100.00%
```

**Comment by Ne02ptzero** [comment]
LGTM :+1:

**Comment by nsampre** [comment]
LGTM

**Comment by quentinselle** [comment]
LGTM !

**Pull request merged**
